# Generated by Django 6.0 on 2025-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_station_trainstop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='fare_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
