# Generated by Django 6.0 on 2026-01-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_train_destination_alter_train_fare_per_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='coaches_count',
            field=models.IntegerField(default=1, help_text='How many carriages does this train have?'),
        ),
        migrations.AddField(
            model_name='trainstop',
            name='first_class_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
