# Generated by Django 6.0 on 2026-01-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_train_coaches_count_trainstop_first_class_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='seats_per_coach',
            field=models.IntegerField(default=80, help_text='Standard is 80 for Economy'),
        ),
        migrations.AlterField(
            model_name='train',
            name='coaches_count',
            field=models.IntegerField(default=8, help_text='Standard is 8 cars'),
        ),
    ]
