# Generated by Django 6.0 on 2026-01-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_train_seats_per_coach_alter_train_coaches_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
